### ISSUE TITLE
Simple figma design for frontend

### ISSUE THREAD

**Issue by benochi** [Code-the-Dream-School/bb-practicum-team-2-front#1]

**Comment by bhoconnor** [comment]
Just trying to make sure i follow, what's the difference between this issue and [this one](https://github.com/Code-the-Dream-School/bb-practicum-team-2-front/issues/3)?

**Comment by benochi** [comment]
One is for an overall site design/theme one was specifically to figure out what the game design will be.  So really just the scope.
